51.  SELECT MAX(SAL) 'SALARIO MÁS ALTO', SUM(COMM) 'TOTAL COMISIONES' , COUNT(EMPNO) 'NÚMERO DE EMPLEADOS' FROM EMP;
52. SELECT * FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE EMPNO=7934 ORDER BY SAL);
53. SELECT ENAME, JOB, SAL FROM EMP WHERE SAL>= SELECT SAL FROM EMP WHERE ENAME='ALLEN';
54. 